# Generated by Django 4.2.1 on 2023-07-13 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='users.wishlist'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='property',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='property.property'),
            preserve_default=False,
        ),
    ]
