# Generated by Django 4.2.1 on 2023-05-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_blog_comment_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comment',
            field=models.CharField(verbose_name=500),
        ),
    ]
