# Generated by Django 4.2.1 on 2023-05-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('num_of_elements', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='images/category/')),
            ],
        ),
    ]
